name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        net-versions: ['3.1.100', '3.1.101','3.1.102','3.1.103','3.1.201']
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: microsoft/mssql-server-linux
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ${{secrets.SqlPassword}}
        ports:
        - 1434:1433         
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.net-versions}}    
    - run: dotnet test "TestProject.sln"
